### ISSUE TITLE
Using Baysor to parallelize within patches

### ISSUE THREAD

**Issue by Marius1311** [gustaveroussy/sopa#201]
**Is your feature request related to a problem? Please describe.**
Since v0.7 (I think), Baysor supports parallelization as well: https://kharchenkolab.github.io/Baysor/dev/configuration/

It's easy to add that to the `Snakefile`, so that several threads can be used within each patch: 
```
  shell:
      """
      export JULIA_NUM_THREADS={resources.cpus_per_task}

      if command -v module &> /dev/null; then
          module purge
      fi

      sopa segmentation baysor {params.sdata_path} --patch-index {wildcards.index} {params.baysor_config}
      """
```

I define the `resources.cpus_per_task` in the workflow config file (for slurm in my case): 

```
    patch_segmentation_baysor:
        mem_mb_per_cpu: 64_00
        runtime: 120
        cpus_per_task: 10
```
