### ISSUE TITLE
Threading options for proseg

### ISSUE THREAD

**Issue by laurie-tonon** [gustaveroussy/sopa#265]
I would like to use sopa on my xenium data with proseg.
The sample is pretty big, 352 594 cells, and I would like to increase the number of threads used by proseg to speed up. 
I ran the snakemake with default parameters and the segmentation step with proseg is still running 25 hours later.
When I tried proseg on my other data I usually increase the --nthreads parameter, but I don't see how I can do that with sopa.

Here is my snakemake command:

```
snakemake \
--config data_path=20250207__105835__cote_SARC_bis/output-XETG00373__0041885__AN23016723_0101__20250207__105944/ \
--configfile=workflow/config/xenium/proseg.yaml \
--workflow-profile workflow/profile/slurm 
```

Thanks a lot for your help

**Comment by quentinblampey** [comment]
Hello @laurie-tonon, you can provide additional parameters to Proseg via the `command_line_suffix` argument in the config, as below. It will be concatenated to the command line before running Proseg.

```yaml
segmentation:
  proseg:
    prior_shapes_key: cell_id # this allows to use the prior segmentation performed by 10X Genomics
    unassigned_value: UNASSIGNED
    command_line_suffix: "--nthreads XXX"
```

NB: How much RAM do you have? I'm still "playing" with Proseg, but its runtime seems to depend very highly on the RAM you have. Consider using 128GB or 256GB of RAM to make it fast (even without the nthread option).

The Proseg support is still relatively new, so please let me know if it works!

**Comment by laurie-tonon** [comment]
Hi,
Thank you, I added the line to my proseg.yaml file and I think it's working, in the log file so far it says it's using 30 threads.
The task is launched via slurm on a node with 256GB of RAM requested. 
What I don't see is how to ask slurm to requested more than on CPU for this task with the Snakemake workflow.
I tried added a "threads" option in the requested ressources but slurm still launch the job with one CPU one one node.
Here is the config.yaml file I use:

```

set-resources:
    explorer:
        mem_mb: 256_000
        slurm_partition: research # use a valid partition/queue name on your cluster (with enough RAM)
    image_write:
        mem_mb: 64_000
        slurm_partition: research # use a valid partition/queue name on your cluster (with a large walltime)
    to_spatialdata:
        mem_mb: 128_000
        slurm_partition: research
    patch_segmentation_baysor:
        mem_mb: 128_000
        slurm_partition: research # use a valid partition/queue name on your cluster (with at least 2h of walltime)
    patch_segmentation_comseg:
        mem_mb: 128_000
        slurm_partition: research
    patch_segmentation_proseg:
        mem_mb: 256_000
        slurm_partition: research
        threads: 32
    aggregate:
        mem_mb: 64_000
        slurm_partition: research
    patchify_transcripts:
        mem_mb: 32_000
        slurm_partition: research
    report:
        mem_mb: 32_000
        slurm_partition: research

# other options (you can keep the default values)
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True

```

Sorry, I'm much more familiar with Nextflow than Snakemake.

Thank you
